### ISSUE TITLE
test with HarmoniSCAO_x

### ISSUE THREAD

**Issue by Teusia** [FabioRossiArcetri/TIPTOP#3]
Hello,

Onto the next issue: I was trying to get the simulation working with any of the HarmoniSCAO_x.ini but I get the following message:

```python
Traceback (most recent call last):

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 554, in compile
    nvrtc.compileProgram(self.ptr, options)

  File "cupy_backends/cuda/libs/nvrtc.pyx", line 108, in cupy_backends.cuda.libs.nvrtc.compileProgram

  File "cupy_backends/cuda/libs/nvrtc.pyx", line 120, in cupy_backends.cuda.libs.nvrtc.compileProgram

  File "cupy_backends/cuda/libs/nvrtc.pyx", line 58, in cupy_backends.cuda.libs.nvrtc.check_status

NVRTCError: NVRTC_ERROR_COMPILATION (6)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "cupy/core/_reduction.pyx", line 764, in cupy.core._reduction.ReductionKernel._get_function

  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret

  File "cupy/core/_reduction.pyx", line 792, in cupy.core._reduction._ReductionKernel_get_cached_function

  File "cupy/core/_reduction.pyx", line 122, in cupy.core._reduction._create_reduction_function

  File "cupy/core/core.pyx", line 1882, in cupy.core.core.compile_with_cache

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 373, in compile_with_cache
    return _compile_with_cache_cuda(

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 440, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 211, in compile_using_nvrtc
    return _compile(source, options, cu_path,

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 195, in _compile
    ptx, mapping = prog.compile(options, log_stream)

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 565, in compile
    raise CompileException(log, self.src, self.name, options,

CompileException: C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(140): error: a value of type "double (*)(const char *)" cannot be used to initialize an entity of type "const double"

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(193): warning: variable "v4" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(199): warning: variable "v6" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(205): warning: variable "v7" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(211): warning: variable "v9" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(217): warning: variable "v11" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(223): warning: variable "v12" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(229): warning: variable "v13" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(235): warning: variable "v15" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(241): warning: variable "v16" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(247): warning: variable "v18" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(253): warning: variable "v20" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(258): warning: variable "v21" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(264): warning: variable "v23" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(270): warning: variable "v25" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(276): warning: variable "v26" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(281): warning: variable "v27" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(286): warning: variable "v28" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(292): warning: variable "v29" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(298): warning: variable "v31" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(303): warning: variable "v32" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(309): warning: variable "v33" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(315): warning: variable "v35" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(320): warning: variable "v36" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(326): warning: variable "v38" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(331): warning: variable "v39" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(337): warning: variable "v40" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(343): warning: variable "v41" is used before its value is set

1 error detected in the compilation of "C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu".


Exception ignored in: 'cupy.core._reduction._AbstractReductionKernel._launch'
Traceback (most recent call last):
  File "cupy/core/_reduction.pyx", line 764, in cupy.core._reduction.ReductionKernel._get_function
  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret
  File "cupy/core/_reduction.pyx", line 792, in cupy.core._reduction._ReductionKernel_get_cached_function
  File "cupy/core/_reduction.pyx", line 122, in cupy.core._reduction._create_reduction_function
  File "cupy/core/core.pyx", line 1882, in cupy.core.core.compile_with_cache
  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 373, in compile_with_cache
    return _compile_with_cache_cuda(
  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 440, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 211, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 195, in _compile
    ptx, mapping = prog.compile(options, log_stream)
  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 565, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(140): error: a value of type "double (*)(const char *)" cannot be used to initialize an entity of type "const double"

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(193): warning: variable "v4" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(199): warning: variable "v6" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(205): warning: variable "v7" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(211): warning: variable "v9" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(217): warning: variable "v11" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(223): warning: variable "v12" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(229): warning: variable "v13" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(235): warning: variable "v15" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(241): warning: variable "v16" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(247): warning: variable "v18" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(253): warning: variable "v20" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(258): warning: variable "v21" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(264): warning: variable "v23" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(270): warning: variable "v25" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(276): warning: variable "v26" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(281): warning: variable "v27" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(286): warning: variable "v28" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(292): warning: variable "v29" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(298): warning: variable "v31" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(303): warning: variable "v32" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(309): warning: variable "v33" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(315): warning: variable "v35" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(320): warning: variable "v36" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(326): warning: variable "v38" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(331): warning: variable "v39" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(337): warning: variable "v40" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu(343): warning: variable "v41" is used before its value is set

1 error detected in the compilation of "C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpmcymji2i\60ee484bd22f77ae7a5699e09ba59c2a_2.cubin.cu".

Traceback (most recent call last):

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 554, in compile
    nvrtc.compileProgram(self.ptr, options)

  File "cupy_backends/cuda/libs/nvrtc.pyx", line 108, in cupy_backends.cuda.libs.nvrtc.compileProgram

  File "cupy_backends/cuda/libs/nvrtc.pyx", line 120, in cupy_backends.cuda.libs.nvrtc.compileProgram

  File "cupy_backends/cuda/libs/nvrtc.pyx", line 58, in cupy_backends.cuda.libs.nvrtc.check_status

NVRTCError: NVRTC_ERROR_COMPILATION (6)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\anne.cheffot\simulations\python\TIPTOP\TIPTOP-EXAMPLE.py", line 29, in <module>
    overallSimulation(fullInputPath, parametersFile, windPsdFile, baseOutpuPath,

  File "C:\Users\anne.cheffot\simulations\python\TIPTOP\tiptop.py", line 115, in overallSimulation
    Ctot               = mLO.computeTotalResidualMatrix(np.array(cartPointingCoords), cartNGSCoords, NGS_flux, NGS_SR, NGS_FWHM_mas)

  File "c:\users\anne.cheffot\simulations\python\tiptop\mastsel\mastsel\mavisLO.py", line 509, in computeTotalResidualMatrix
    bias, amu, avar = self.computeBias(aNGS_flux[starIndex]/self.N_sa_tot_LO, aNGS_SR_1650[starIndex], aNGS_FWHM_mas[starIndex]) # one scalar, two tuples of 2

  File "c:\users\anne.cheffot\simulations\python\tiptop\mastsel\mastsel\mavisLO.py", line 294, in computeBias
    mu_ktr_array, var_ktr_array, sigma_ktr_array = self.meanVarSigma(f_k_data)

  File "c:\users\anne.cheffot\simulations\python\tiptop\mastsel\mastsel\mavisLO.py", line 239, in meanVarSigma
    xplot1, mu_ktr_array = self.compute2DMeanVar( self.aFunctionM, self.expr0M, gaussianPoints)

  File "c:\users\anne.cheffot\simulations\python\tiptop\mastsel\mastsel\mavisLO.py", line 232, in compute2DMeanVar
    ssx, s0 = self.mIt.functionEval(expr0, paramsAndRanges )

  File "c:\users\anne.cheffot\simulations\python\tiptop\seeing\seeing\integrator.py", line 94, in functionEval
    return self.outputData(parameterSamplings), self.outputData(self.parametricEvaluation(parameterSamplings, lambdaIntegrand))

  File "c:\users\anne.cheffot\simulations\python\tiptop\seeing\seeing\integrator.py", line 78, in parametricEvaluation
    return evaluableFunction(*paramsSamplingGrids)

  File "cupy/core/fusion.pyx", line 925, in cupy.core.fusion.Fusion.__call__

  File "cupy/core/_kernel.pyx", line 821, in cupy.core._kernel.ElementwiseKernel.__call__

  File "cupy/core/_kernel.pyx", line 846, in cupy.core._kernel.ElementwiseKernel._get_elementwise_kernel

  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret

  File "cupy/core/_kernel.pyx", line 639, in cupy.core._kernel._get_elementwise_kernel

  File "cupy/core/_kernel.pyx", line 37, in cupy.core._kernel._get_simple_elementwise_kernel

  File "cupy/core/_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel

  File "cupy/core/core.pyx", line 1882, in cupy.core.core.compile_with_cache

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 373, in compile_with_cache
    return _compile_with_cache_cuda(

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 440, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 211, in compile_using_nvrtc
    return _compile(source, options, cu_path,

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 195, in _compile
    ptx, mapping = prog.compile(options, log_stream)

  File "C:\Users\anne.cheffot\anaconda3\envs\gmtsim\lib\site-packages\cupy\cuda\compiler.py", line 565, in compile
    raise CompileException(log, self.src, self.name, options,

CompileException: C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpxb4vvmus\0e2909c5ff4c514e783712638ac7d536_2.cubin.cu(60): error: a value of type "double (*)(const char *)" cannot be used to initialize an entity of type "const double"

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpxb4vvmus\0e2909c5ff4c514e783712638ac7d536_2.cubin.cu(80): warning: variable "v2" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpxb4vvmus\0e2909c5ff4c514e783712638ac7d536_2.cubin.cu(86): warning: variable "v4" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpxb4vvmus\0e2909c5ff4c514e783712638ac7d536_2.cubin.cu(92): warning: variable "v6" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpxb4vvmus\0e2909c5ff4c514e783712638ac7d536_2.cubin.cu(98): warning: variable "v8" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpxb4vvmus\0e2909c5ff4c514e783712638ac7d536_2.cubin.cu(103): warning: variable "v9" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpxb4vvmus\0e2909c5ff4c514e783712638ac7d536_2.cubin.cu(108): warning: variable "v10" is used before its value is set

C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpxb4vvmus\0e2909c5ff4c514e783712638ac7d536_2.cubin.cu(114): warning: variable "v11" is used before its value is set

1 error detected in the compilation of "C:\Users\ANNE~1.CHE\AppData\Local\Temp\tmpxb4vvmus\0e2909c5ff4c514e783712638ac7d536_2.cubin.cu".
```

I use the following versions of the cuda suite:
cudatoolkit               10.1.243             h74a9793_0
cudnn                     7.6.5                cuda10.1_0
cupy                      8.3.0            py39hd4ca531_0

I tried to update to a more recent version of cupy/cuda 
cudatoolkit               11.6.0              hc0ea762_10    conda-forge
cupy                      10.2.0           py39hc474d4a_0    conda-forge

And it yield a similar result. 
Since it seem to fail during a compilation operation, I looked it up and it looks like the cuda toolkit needs Visual studio for it's compiler. How ever I already have that installed. Unless it does not detect it this cannot be the problem.

**Comment by Teusia** [comment]
The problem was actually that some combination of parameter could not be computed because there was a square root of -1 somewhere and for this computation only real numbers are allowed. This was solved by testing the value before trying to compute and raising an error if the value would give a non real number.
